services:
  - type: web
    name: keystroker-auth-backend
    region: oregon
    plan: free
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: keystroker_auth
      - key: CORS_ORIGINS
        value: "https://keystroker.vercel.app"
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
